# Generated by Django 4.0.1 on 2022-01-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='id_match',
        ),
    ]
