# Generated by Django 4.0.1 on 2022-01-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_match_id_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
