# Generated by Django 4.0.1 on 2022-01-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_test_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('poste', models.CharField(max_length=2)),
                ('id_team', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Score_NBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bplayer', models.IntegerField()),
                ('id_match', models.IntegerField()),
                ('score', models.IntegerField()),
                ('time_play', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='can_bet',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
