# Generated by Django 4.0.1 on 2022-01-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_b_player_score_nbl_team_match_can_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='id_match',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
