# Generated by Django 4.0.1 on 2022-01-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_team_code_alter_team_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_player',
            name='poste',
            field=models.CharField(max_length=5),
        ),
    ]
