# Generated by Django 4.0.1 on 2022-02-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_b_player_poste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('match_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
