# Generated by Django 4.0.1 on 2022-02-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_bet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='match_id',
        ),
    ]
