# Generated by Django 4.0.1 on 2022-02-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_bet_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='match_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
