# Generated by Django 4.0.1 on 2022-03-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_bet_match_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.CharField(max_length=20)),
                ('score_tot', models.IntegerField()),
                ('id_user', models.IntegerField()),
            ],
        ),
    ]
